version: "2"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=webchat
      - POSTGRES_USER=facu
      - POSTGRES_PASSWORD=admin1234
    ports:
      - 5432:5432
    volumes:
      - ./postgres_db:/var/lib/postgresql/data